### ISSUE TITLE
分享两篇关于成长的文章

### ISSUE THREAD

**Issue by xiongwilee** [ACoderHIT/weekly_article#3]
https://mp.weixin.qq.com/s/-fL9tqT96ARubwaXAXYH7A
《核心团队是剩下来的，而不是选出来的》
核心团队必须建立深层的连接与信任，因而必须是经风雨后见彩虹。中层的人只有与你一起历经磨难，身上既有无数个伤疤、又有无数个军功章后，才能进入核心团队。

https://coolshell.cn/articles/20276.html
《别让自己“墙”了自己》
2019年年初，我面试了一个很年轻的小伙子（93/94年出生），这个小伙子特别有灵性，也很聪明，计算机专业出身，也很喜欢技术，基础和学习能力也很好……然而，这个小伙子有两大喜好：1）只愿（或是说被迫）呆在一个毫无IT的环境的三/四线城市，2）对技术有非常大的偏好，只喜欢Go语言，非常不喜欢其它的语言……保持开放的心态，知而获智，智达高远。

**Comment by ACoderHIT** [comment]
已收录进2019-12-13日的周刊
