### ISSUE TITLE
转几个圈内新闻

### ISSUE THREAD

**Issue by xiongwilee** [ACoderHIT/weekly_article#5]
> https://www.infoq.cn/article/ZLY8QbmqUXzPxpSu5ipG
《刚刚！达摩院宣布十大技术趋势，AI 有望迈过两大关键门槛》
冯·诺伊曼架构的存储和计算分离已经不适合数据驱动的人工智能应用需求，人工智能结合LoT万物互联时代即将来临。

> https://www.infoq.cn/article/ImyZHFuUpoewipIXttg7
《InfoQ 编辑部开年聊聊 2020 年值得关注的十大技术趋势》
容器化、Service Mesh、Serverless、WebAssembly、人工智能、区块链不出意外纷纷入榜

> https://www.infoq.cn/article/kzc9yYIekjvwuOD0jyuh
《2019 年 IT 互联网十大“车祸”现场》
当好吃瓜群众，观望互联网翻车现场，李彦宏被泼水上榜

**Comment by ACoderHIT** [comment]
done
